# Site settings
title: CodeGaucho blog
email: tom@codegaucho.com
description: > # this means to ignore newlines until "baseurl:"
  A Jekyll based blog for recording odds and ends related to the CodeGaucho efforts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ghpages.codegaucho.com" # the base hostname & protocol for your site
twitter_username: codegaucho
github_username:  codegaucho
cloudinary_id: codegaucho
freefind: 80379214

collections:
  projects:
    output: true

defaults:
  -
    scope:
      type: projects
    values:
      layout: project
      image_options: "c_scale,w_320"
      thumbnail_options: "c_scale,w_320"
      active_nav: Projects
      sitemap:
        priority: 0.8
        changefreq: 'monthly'

# Build settings
markdown: kramdown
